---
- name: Create Azure Resource Group
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    azure_tenant_id: "{{ lookup('env','CUSTOM_CRED_AZURE_TENANT_ID') }}"
    azure_subscription_id: "{{ lookup('env','CUSTOM_CRED_AZURE_SUBSCRIPTION_ID') }}"
    azure_client_id: "{{ lookup('env','CUSTOM_CRED_AZURE_CLIENT_ID') }}"
    azure_client_secret: "{{ lookup('env','CUSTOM_CRED_AZURE_CLIENT_SECRET') }}"
  vars_files:
    - ./vars/vars.yml
  roles:
    - { role: Azure.azure_preview_modules }
    - { role: az_naming_convention }
    - { role: az_create_resource_group }
    #- { role: az_create_virtual_network }
    #- { role: az_create_virtual_subnet }
    #- { role: az_create_network_security_group }
    #- { role: az_create_network_interface_card }
    #- { role: az_create_}
...
