---
- name: Create Azure Resource Group
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ./vars/vault.yml
    - ./vars/vars.yml
  roles:
    - { role: Azure.azure_preview_modules }
    - { role: rdtechie.az_create_resource_group  }
...